------------------------------------------------------------- STG Table DDL --------------------------------------------------------------

CREATE MULTISET TABLE VS186038.STG_AZURE_RETAIL_TRANSACTION ,FALLBACK , 
 
   NO BEFORE JOURNAL, 
 
   NO AFTER JOURNAL, 
 
   CHECKSUM = DEFAULT, 
 
 
   DEFAULT MERGEBLOCKRATIO (
 
      Transaction_ID VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC, 
 
      Coupon_Code VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC, 
 
      Coupon_Type VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC, 
 
      Created_At VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC, 
 
      Customer_Name VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,  
 
      Customer_Review VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
	  
	  Gross_Margin VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
	  
	  Order_Type VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
	  
	  Payment_Type VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
	  Amount VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
	  Serving_Time VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
	  Txn_Id VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
	  Product_Id VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
	  Store_Id VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
	  Customer_id VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
 
      Source_System VARCHAR(10)CHARACTER SET LATIN NOT CASESPECIFIC, 
 
      LOAD_DTTM TIMESTAMP(0)
     ) PRIMARY INDEX (Transaction_ID );

