CREATE MULTISET TABLE MP255078.CORE_AZURE_RETAIL_PRODUCT ,FALLBACK , 
   NO BEFORE JOURNAL, 
   NO AFTER JOURNAL, 
   CHECKSUM = DEFAULT, 
   DEFAULT MERGEBLOCKRATIO (

      id Integer NOT NULL, 
      Product_Category VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC, 
      Product_Cost Decimal(6,2), 
      Product_Name VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC, 
      Recomsale_Price Decimal(6,2) ,  
      Serving_Size VARCHAR(100) CHARACTER SET LATIN COMPRESS ('VENTI','LARGE','GRANDE') NOT CASESPECIFIC ,
	  Source_System VARCHAR(10) CHARACTER SET LATIN  COMPRESS ('AZURE') NOT CASESPECIFIC NOT NULL,
	  EFF_START_DTTM TIMESTAMP(0) NOT NULL,
	  EFF_END_DTTM TIMESTAMP(0) NOT NULL,
	  CURR_IND char(1)  COMPRESS ('Y','N') NOT NULL,
	  LOAD_DTTM TIMESTAMP(0) NOT NULL
     ) PRIMARY INDEX (id )
	 PARTITION BY ( RANGE_N(CAST((EFF_START_DTTM ) AS DATE AT TIME ZONE INTERVAL '3:00' HOUR TO MINUTE  ) BETWEEN DATE '2017-01-01' AND DATE '2050-12-31' EACH INTERVAL '1' DAY ,
NO RANGE, UNKNOWN))INDEX ( EFF_END_DTTM )


replace view MP255078.CORE_AZURE_RETAIL_PRODUCT_VIEW AS 
LOCKING ROW FOR ACCESS
SELECT * FROM MP255078.CORE_AZURE_RETAIL_PRODUCT ;

