CREATE MULTISET TABLE MP255078.CORE_AZURE_RETAIL_CUSTOMER ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      Cust_id INTEGER NOT NULL,
      Age INTEGER ,
      Gender CHAR(1) CHARACTER SET LATIN COMPRESS ('M','F') NOT CASESPECIFIC ,
      Cust_Name VARCHAR(1000) CHARACTER SET LATIN CASESPECIFIC,
      Source_System VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	  EFF_START_DTTM TIMESTAMP(0) NOT NULL,
	  EFF_END_DTTM TIMESTAMP(0) NOT NULL,
	  CURR_IND char(1) NOT NULL,
	  LOAD_DTTM TIMESTAMP(0) NOT NULL
     ) PRIMARY INDEX (Cust_id )
	 PARTITION BY ( RANGE_N(CAST((EFF_START_DTTM ) AS DATE AT TIME ZONE INTERVAL '3:00' HOUR TO MINUTE  ) BETWEEN DATE '2017-01-01' AND DATE '2050-12-31' EACH INTERVAL '1' DAY ,
NO RANGE, UNKNOWN))INDEX ( EFF_END_DTTM )
;


replace view MP255078.CORE_AZURE_RETAIL_CUSTOMER_VIEW AS 
LOCKING ROW FOR ACCESS
SELECT * FROM MP255078.CORE_AZURE_RETAIL_CUSTOMER ;
