CREATE MULTISET TABLE MP255078.STG_AZURE_RETAIL_CUSTOMER ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      Cust_id VARCHAR(255) CHARACTER SET LATIN CASESPECIFIC,
      Age VARCHAR(255) CHARACTER SET LATIN CASESPECIFIC,
      Gender VARCHAR(1000) CHARACTER SET LATIN CASESPECIFIC,
      Cust_name VARCHAR(1000) CHARACTER SET LATIN CASESPECIFIC,
      LOAD_DTTM TIMESTAMP(6))
 PRIMARY INDEX (Cust_id);
 
 
replace view MP255078.STG_AZURE_RETAIL_CUSTOMER_VIEW AS 
LOCKING ROW FOR ACCESS
SELECT * FROM MP255078.STG_AZURE_RETAIL_CUSTOMER ;