CREATE TABLE MP255078.RETAIL_CUSTOMER_QUEUE ,QUEUE ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      QITS TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	  Cust_id INTEGER NOT NULL,
      Age INTEGER,
      Gender CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC ,
      Cust_Name VARCHAR(255) CHARACTER SET LATIN CASESPECIFIC,
      LOAD_DTTM TIMESTAMP(6))
PRIMARY INDEX ( QITS );


REPLACE PROCEDURE CUSTOMER_PROC ()
BEGIN
   INSERT INTO MP255078.RETAIL_CUSTOMER_QUEUE (Cust_id, Age, Gender,Cust_name, LOAD_DTTM)
   CURRENT VALIDTIME SELECT Cust_id, Age, Gender,Cust_name,LOAD_DTTM FROM MP255078.CORE_AZURE_RETAIL_CUSTOMER
         WHERE CAST(LOAD_DTTM AS DATE)  = CURRENT_DATE ;
END;


----STEPS TO EXECUTE 

/*


CALL MP255078.CUSTOMER_PROC ();

SELECT COUNT(1) FROM MP255078.RETAIL_CUSTOMER_QUEUE;


SELECT AND CONSUME TOP 1 * FROM MP255078.RETAIL_CUSTOMER_QUEUE;
SELECT AND CONSUME TOP 1 * FROM MP255078.RETAIL_CUSTOMER_QUEUE;
SELECT AND CONSUME TOP 1 * FROM MP255078.RETAIL_CUSTOMER_QUEUE;

SELECT COUNT(1) FROM MP255078.RETAIL_CUSTOMER_QUEUE;             ------- CHECK IF 3 RECORDS HAVE REDUCED FROM TABLE



*/











