CREATE MULTISET TABLE RK250076.SEM_NOS_AWS_ORDERS ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      LOCATION VARCHAR(2048) CHARACTER SET UNICODE,
      THEYEAR INTEGER,
      THEMONTH INTEGER,
      SALES_DATE DATE,
      CUSTOMER_ID INTEGER,
      STORE_ID INTEGER ,
      BASKET_ID INTEGER,
      PRODUCT_ID INTEGER,
      SALES_QUANTITY INTEGER,
      DISCOUNT_AMOUNT FLOAT,
      SOURCE_SYSTEM VARCHAR(6) CHARACTER SET LATIN CASESPECIFIC,
      LOAD_DTTM TIMESTAMP(0))
PRIMARY INDEX ( CUSTOMER_ID );


    
GRANT SELECT ON RK250076.SEM_NOS_AWS_ORDERS TO MP255078 WITH GRANT OPTION;
GRANT SELECT ON RK250076.SEM_NOS_AWS_ORDERS TO AR186005 WITH GRANT OPTION;
GRANT SELECT ON RK250076.SEM_NOS_AWS_ORDERS TO SK186103 WITH GRANT OPTION;	     


