---- QRDER_QTY BY CUSTOMER_ID ----
REPLACE VIEW RK250076.SEM_ORDER_QTY_BY_CUSTOMER_ID_VW (CUSTOMER_ID, ORDER_SALES_DATE, ORDER_SALES_QUANTITY, SOURCE_SYSTEM) AS 
SEL CUST_ID, ORDER_DATE, SUM(ORDER_QTY) AS CURRENT_ORDER_QTY, 'ORDERS_ONETIME' AS SOURCE_SYSTEM FROM RK250076.SEM_AWS_ORDERS GROUP BY CUST_ID, ORDER_DATE
UNION ALL
SEL CUSTOMER_ID, SALES_DATE AS HISTORIC_SALES_DATE, SUM(SALES_QUANTITY) AS HISTORIC_SALES_QUANTITY, 'NOS_DATA' AS SOURCE_SYSTEM FROM RK250076.SEM_NOS_AWS_ORDERS@TDPRD2_FS GROUP BY CUSTOMER_ID, SALES_DATE;




---- QRDER_QTY BY STORE_ID ----
REPLACE VIEW RK250076.SEM_ORDER_QTY_BY_STORE_ID_VW (STORE_ID, ORDER_SALES_DATE, ORDER_SALES_QUANTITY, SOURCE_SYSTEM) AS 
SEL STORE_ID, ORDER_DATE, SUM(ORDER_QTY) AS CURRENT_ORDER_QTY, 'ORDERS_ONETIME' AS SOURCE_SYSTEM FROM RK250076.SEM_AWS_ORDERS GROUP BY STORE_ID, ORDER_DATE
UNION ALL
SEL STORE_ID, SALES_DATE AS HISTORIC_SALES_DATE, SUM(SALES_QUANTITY) AS HISTORIC_SALES_QUANTITY, 'NOS_DATA' AS SOURCE_SYSTEM FROM RK250076.SEM_NOS_AWS_ORDERS@TDPRD2_FS GROUP BY STORE_ID, SALES_DATE;




---- QRDER_QTY BY CUSTOMER_ID, STORE_ID ----
REPLACE VIEW RK250076.SEM_ORDER_QTY_BY_CUSTOMER_STORE_ID_VW (CUSTOMER_ID, STORE_ID, ORDER_SALES_DATE, ORDER_SALES_QUANTITY, SOURCE_SYSTEM) AS 
SEL CUST_ID, STORE_ID, ORDER_DATE, SUM(ORDER_QTY) AS CURRENT_ORDER_QTY, 'ORDERS_ONETIME' AS SOURCE_SYSTEM FROM RK250076.SEM_AWS_ORDERS GROUP BY CUST_ID, STORE_ID, ORDER_DATE
UNION ALL
SEL CUSTOMER_ID, STORE_ID, SALES_DATE AS HISTORIC_SALES_DATE, SUM(SALES_QUANTITY) AS HISTORIC_SALES_QUANTITY, 'NOS_DATA' AS SOURCE_SYSTEM FROM RK250076.SEM_NOS_AWS_ORDERS@TDPRD2_FS 
GROUP BY CUSTOMER_ID, STORE_ID, SALES_DATE;


